services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: StudentHelper
      POSTGRES_PASSWORD: N54#take67TUESfsr99
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mysite_backend
    ports:
      - "8080:8080"
    volumes:
    - ./src:/app/src
    - ./pom.xml:/app/pom.xml
    - ./target:/app/target
    command: mvn spring-boot:run
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: StudentHelper
      SPRING_DATASOURCE_PASSWORD: N54#take67TUESfsr99

volumes:
  db_data:
